"""empty message

Revision ID: 5677b40f377
Revises: None
Create Date: 2014-03-24 16:14:01.063310

"""

# revision identifiers, used by Alembic.
revision = '5677b40f377'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_key', sa.String(length=32), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('saved_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_data')
    ### end Alembic commands ###
